---
## Phase III : Advance operation with Business example and more operation with numpy array. 
---


---
### Explanation of the Code in this Notebook
---

#### 1. **Introduction to Advanced Operations**
The notebook begins with an introduction to advanced operations using NumPy arrays, focusing on real-world business examples. It sets the stage for performing data analysis and mathematical operations on structured datasets.

#### 2. **Dataset of Restaurant Sales**
A dataset is created using a NumPy array to represent the yearly sales data of 10 restaurants over four years (2021–2024). Each row corresponds to a restaurant, and the columns represent the restaurant ID and yearly sales.

#### 3. **Basic Analysis of Sales Data**
- **Shape and Slicing:** The shape of the dataset is printed to understand its dimensions, and slicing is used to extract data for the first three restaurants.
- **Yearly Sales:** The total sales for each year across all restaurants are calculated using `np.sum()`.
- **Minimum and Maximum Sales:** The minimum and maximum yearly sales for each restaurant are computed using `np.min()` and `np.max()`.
- **Average Sales:** The average yearly sales for each restaurant are calculated using `np.mean()`.
- **Cumulative Sales:** The cumulative sales for each restaurant over the years are computed using `np.cumsum()`.

#### 4. **Additional Vector Operations**
- **Vector Arithmetic:** Two vectors are created, and element-wise addition and multiplication are performed.
- **Dot Product:** The dot product of the two vectors is calculated.
- **Angle Between Vectors:** The angle between the two vectors is computed using the dot product formula and `np.arccos()`.

#### 5. **Vectorization and Broadcasting**
- A NumPy array of restaurant types is defined.
- A vectorized function is created using `np.vectorize()` to convert strings to uppercase, demonstrating the power of vectorization for string operations.

#### 6. **Monthly Average Sales**
- The monthly average sales for each restaurant are calculated by dividing the yearly sales data by 12. -  This provides insights into the average monthly performance of each restaurant.
---


In [2]:
import numpy as np

---
### Dataset of 10 restaurants with there sales :-
---

In [3]:

# the data in the following format:
# sales_data = [restaurant_id, sales_2021, sales_2022, sales_2023, sales_2024]
# Using a small portion of actual data from a trusted site
# For the sake of this example, let's use hypothetical sales data for well-known restaurants

sales_data = np.array([
    [1, 50000, 52000, 54000, 56000],  # McDonald's
    [2, 45000, 47000, 49000, 51000],  # Starbucks
    [3, 40000, 42000, 44000, 46000],  # Subway
    [4, 35000, 37000, 39000, 41000],  # Burger King
    [5, 30000, 32000, 34000, 36000],  # Wendy's
    [6, 25000, 27000, 29000, 31000],  # Taco Bell
    [7, 20000, 22000, 24000, 26000],  # Dunkin' Donuts
    [8, 15000, 17000, 19000, 21000],  # Pizza Hut
    [9, 10000, 12000, 14000, 16000],  # KFC
    [10, 5000, 7000, 9000, 11000]     # Domino's
])

print("===== Sales analysis =====")
print("Sales data size(shape): ",sales_data.shape)
print("the Sales data of first 3 restaurants : \n", sales_data[:3])
# for i in range(3): print(sales_data[i]) instead of this we use slicing



===== Sales analysis =====
Sales data size(shape):  (10, 5)
the Sales data of first 3 restaurants : 
 [[    1 50000 52000 54000 56000]
 [    2 45000 47000 49000 51000]
 [    3 40000 42000 44000 46000]]


In [4]:
# total year sales 
print("yearly sales : \n", np.sum(sales_data[:, 1:],axis=0))
print("minimum sales per restaurant : \n", np.min(sales_data[:, 1:],axis=1))
print("maximum sales per restaurant: \n", np.max(sales_data[:, 1:],axis=1))

# average sales using mean 
print("the average sales of each restaurant : ", np.mean(sales_data[:,1:], axis=1))

# cumlative sales of restaurants 
print("cumalative sales : \n", np.cumulative_sum(sales_data[:,1:], axis=1))



yearly sales : 
 [275000 295000 315000 335000]
minimum sales per restaurant : 
 [50000 45000 40000 35000 30000 25000 20000 15000 10000  5000]
maximum sales per restaurant: 
 [56000 51000 46000 41000 36000 31000 26000 21000 16000 11000]
the average sales of each restaurant :  [53000. 48000. 43000. 38000. 33000. 28000. 23000. 18000. 13000.  8000.]
cumalative sales : 
 [[ 50000 102000 156000 212000]
 [ 45000  92000 141000 192000]
 [ 40000  82000 126000 172000]
 [ 35000  72000 111000 152000]
 [ 30000  62000  96000 132000]
 [ 25000  52000  81000 112000]
 [ 20000  42000  66000  92000]
 [ 15000  32000  51000  72000]
 [ 10000  22000  36000  52000]
 [  5000  12000  21000  32000]]


---

---
## Aditional vector operations
---

In [5]:
# Create two NumPy arrays representing vectors
vector1 = np.array([1,2,3,4,5])
vector2 = np.array([6,7,8,9,10])

# Element-wise addition of vectors
# This adds corresponding elements: [1+6, 2+7, 3+8, 4+9, 5+10]
print("\nVector addition : ", vector1+vector2)

# Element-wise multiplication of vectors (Hadamard product)
# This multiplies corresponding elements: [1*6, 2*7, 3*8, 4*9, 5*10]
print("\nVector multiplication : ", vector1*vector2)

# Dot product calculation: sum of products of corresponding elements
# (1*6 + 2*7 + 3*8 + 4*9 + 5*10)
print("\nDot product :", np.dot(vector1,vector2))

# Calculate the angle between two vectors using the dot product formula:
# θ = arccos[(v1·v2)/(|v1|*|v2|)]
# np.linalg.norm() calculates the magnitude (length) of each vector

angle = np.arccos(np.dot(vector1,vector2)/((np.linalg.norm(vector1)*np.linalg.norm(vector2))))
print("angle is :",angle)  # Result is in radians


Vector addition :  [ 7  9 11 13 15]

Vector multiplication :  [ 6 14 24 36 50]

Dot product : 130
angle is : 0.26554161733900966


---
### vectorization and broadcasting
---

In [6]:
# Define an array of restaurant types
restaurant_types = np.array(['biryani', 'chinese', 'indian', 'continental'])

# Create a vectorized function to convert strings to uppercase
vectorized_upper = np.vectorize(str.upper)

# Apply the vectorized function to the restaurant types array and print the result
print("Restaurants name in uppercase: ", vectorized_upper(restaurant_types))


Restaurants name in uppercase:  ['BIRYANI' 'CHINESE' 'INDIAN' 'CONTINENTAL']


In [7]:
# Calculate the monthly average sales for each restaurant
# Divide the yearly sales data (columns 1 to end) by 12
monthly_avg = sales_data[:, 1:] / 12

# Print the calculated monthly average sales
print(monthly_avg)

[[4166.66666667 4333.33333333 4500.         4666.66666667]
 [3750.         3916.66666667 4083.33333333 4250.        ]
 [3333.33333333 3500.         3666.66666667 3833.33333333]
 [2916.66666667 3083.33333333 3250.         3416.66666667]
 [2500.         2666.66666667 2833.33333333 3000.        ]
 [2083.33333333 2250.         2416.66666667 2583.33333333]
 [1666.66666667 1833.33333333 2000.         2166.66666667]
 [1250.         1416.66666667 1583.33333333 1750.        ]
 [ 833.33333333 1000.         1166.66666667 1333.33333333]
 [ 416.66666667  583.33333333  750.          916.66666667]]
