
---

## PHASE I : Introduction to the NumPy array and its basics.

NumPy is a fundamental package for scientific computing with Python. It provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

Special thanks to Hitesh Sir and the Chai aur Code YouTube channel for providing such a good NumPy course.

---

---

### Why Use NumPy?

NumPy, short for Numerical Python, is a powerful library for numerical computing in Python. It provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. Here are some reasons why we use NumPy:

#### Performance
NumPy is highly optimized for performance. It is implemented in C and Fortran, which allows it to perform operations much faster than standard Python lists. This is particularly important for large datasets and complex mathematical computations.

#### Memory Efficiency
NumPy arrays are more memory-efficient than Python lists. They require less memory to store data, which is crucial when working with large datasets.

#### Broadcasting
NumPy supports broadcasting, a powerful mechanism that allows arithmetic operations to be performed on arrays of different shapes. This feature simplifies code and improves performance by avoiding the need for explicit loops.

#### Vectorization
NumPy allows for vectorized operations, which means that operations can be applied to entire arrays at once, rather than element by element. This leads to more concise and readable code, and also takes advantage of low-level optimizations.

#### Comprehensive Functionality
NumPy provides a wide range of mathematical functions, including linear algebra, statistical operations, and random number generation. This makes it a versatile tool for scientific computing.

#### Integration with Other Libraries
NumPy is the foundation for many other scientific computing libraries in Python, such as SciPy, pandas, and scikit-learn. Its compatibility and integration with these libraries make it an essential tool for data analysis and machine learning.

#### Community and Documentation
NumPy has a large and active community, which means that it is well-maintained and continuously improved. Additionally, it has extensive documentation and numerous tutorials available, making it accessible for both beginners and experienced users.

---

In [2]:
import numpy as np
import time

---
### Creating NumPy array :-
---

In [3]:
# array is a collection of elements of the same type it can be of multiple dimensions
# 1D array is a list of elements also called as vector
# 2D array is a list of lists also called as matrix
# 3D array is a list of list of lists and so on , more than 2d the formed can be called as tensor

arr_1D = np.array([1,2,3,4,5,6,7,8,9])
print(f"1D array is {arr_1D}")

arr_2D = np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(f"2D array is {arr_2D}")

1D array is [1 2 3 4 5 6 7 8 9]
2D array is [[1 2 3 4 5]
 [5 4 3 2 1]]


---
### List vs Numpy array :-
---

In [4]:
py_list = [1,2,3,4]
print(f"Python list multiplication : {py_list * 2}")


np_array = np.array([1,2,3,4])
print(f"Numpy array multiplication : {np_array * 2}")

start = time.time()
py_list = [i*2 for i in range(1000000)]
print(f"time taken to complete this operation : {time.time()- start}")

start = time.time()
np_array = np.arange(1000000) * 2
print(f"time taken to complete this operation : {time.time()- start}")  # from results numpy is faster than python list

Python list multiplication : [1, 2, 3, 4, 1, 2, 3, 4]
Numpy array multiplication : [2 4 6 8]
time taken to complete this operation : 0.13720273971557617
time taken to complete this operation : 0.09682154655456543


---
### Creating array from Scratch :-
---

In [5]:
zeros = np.zeros((4,4))          # for creating zero array
print("zero array : \n",zeros)


ones = np.ones((4,4))            # for creating ones array
print("ones array : \n",ones)


full = np.full((4,4), 4)         # for creating full array
print("full array : \n ", full)

random = np.random.random((4,4)) # for creating random array
print("random array : \n", random)

sequence = np.arange(0,10,2)     # for creating sequence array
print("sequence array : \n", sequence)

zero array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array : 
  [[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
random array : 
 [[0.12001402 0.89633495 0.46603549 0.67902307]
 [0.87127362 0.19113104 0.84561587 0.20729569]
 [0.91463534 0.30892007 0.88598553 0.02360877]
 [0.91169586 0.58126265 0.22560175 0.59538291]]
sequence array : 
 [0 2 4 6 8]


---
### Vector, Matrix and tensor :-
---

In [6]:
vector = np.array([1,2,3,4])
print("vector : \n ",vector)
# vector is a 1D array 

matrix = np.array([[1,2,3,4],
                   [5,6,7,8]])
print("matrix : \n", matrix)
# matrix is a 2D array

tensor = np.array([[[1,2],[3,4]],[[2,1],[4,3]],[[5,6],[6,7]]])
print("tensor : \n",tensor)
# tensor is a array with more than 2 dimensions

vector : 
  [1 2 3 4]
matrix : 
 [[1 2 3 4]
 [5 6 7 8]]
tensor : 
 [[[1 2]
  [3 4]]

 [[2 1]
  [4 3]]

 [[5 6]
  [6 7]]]


---
### Array properties :-
---

In [7]:
ny_array = np.array([[1,2,3,4],
                     [4,3,2,1],
                     [0,0,0,0]])

print("shape : ",ny_array.shape)      # for getting the shape of the array

print("Dimension : ",ny_array.ndim)   # for getting the dimension of the array

print("size : ",ny_array.size)        # for getting the size of the array

print("Dtype : ",ny_array.dtype)      # for getting the data type of the array


shape :  (3, 4)
Dimension :  2
size :  12
Dtype :  int64


---
### Array reshaping :-
---

In [8]:
array = np.array([1,2,3,4,5,6,7,8,8,9])
print("Normal array : ",array)

reshaped = array.reshape((2,5))    # for reshaping the array
print("reshaped array : \n",reshaped)

flattened = reshaped.flatten()     # for flattening the array
print("flattened array : ",flattened)

# ravel only  return the view , instead of copy

raveled = reshaped.ravel()         # for raveling the array
print("raveled array : ",raveled)

# transpose is used for transposing the array
transpose = reshaped.T             # for transposing the array
print("transposed array : \n ",transpose)

Normal array :  [1 2 3 4 5 6 7 8 8 9]
reshaped array : 
 [[1 2 3 4 5]
 [6 7 8 8 9]]
flattened array :  [1 2 3 4 5 6 7 8 8 9]
raveled array :  [1 2 3 4 5 6 7 8 8 9]
transposed array : 
  [[1 6]
 [2 7]
 [3 8]
 [4 8]
 [5 9]]
