---
## Phase III : Advance operation with Business example and more operation with numpy array. 
---

In [4]:
import numpy as np

---
### Dataset of 10 restaurants with there sales :-
---

In [5]:

# the data in the following format:
# sales_data = [restaurant_id, sales_2021, sales_2022, sales_2023, sales_2024]
# Using a small portion of actual data from a trusted site
# For the sake of this example, let's use hypothetical sales data for well-known restaurants

sales_data = np.array([
    [1, 50000, 52000, 54000, 56000],  # McDonald's
    [2, 45000, 47000, 49000, 51000],  # Starbucks
    [3, 40000, 42000, 44000, 46000],  # Subway
    [4, 35000, 37000, 39000, 41000],  # Burger King
    [5, 30000, 32000, 34000, 36000],  # Wendy's
    [6, 25000, 27000, 29000, 31000],  # Taco Bell
    [7, 20000, 22000, 24000, 26000],  # Dunkin' Donuts
    [8, 15000, 17000, 19000, 21000],  # Pizza Hut
    [9, 10000, 12000, 14000, 16000],  # KFC
    [10, 5000, 7000, 9000, 11000]     # Domino's
])

print("===== Sales analysis =====")
print("Sales data size(shape): ",sales_data.shape)
print("the Sales data of first 3 restaurants : \n", sales_data[:3])
# for i in range(3): print(sales_data[i]) instead of this we use slicing



===== Sales analysis =====
Sales data size(shape):  (10, 5)
the Sales data of first 3 restaurants : 
 [[    1 50000 52000 54000 56000]
 [    2 45000 47000 49000 51000]
 [    3 40000 42000 44000 46000]]


In [6]:
# total year sales 
print("yearly sales : \n", np.sum(sales_data[:, 1:],axis=0))
print("minimum sales per restaurant : \n", np.min(sales_data[:, 1:],axis=1))
print("maximum sales per restaurant: \n", np.max(sales_data[:, 1:],axis=1))

# average sales using mean 
print("the average sales of each restaurant : ", np.mean(sales_data[:,1:], axis=1))

# cumlative sales of restaurants 
print("cumalative sales : \n", np.cumulative_sum(sales_data[:,1:], axis=1))



yearly sales : 
 [275000 295000 315000 335000]
minimum sales per restaurant : 
 [50000 45000 40000 35000 30000 25000 20000 15000 10000  5000]
maximum sales per restaurant: 
 [56000 51000 46000 41000 36000 31000 26000 21000 16000 11000]
the average sales of each restaurant :  [53000. 48000. 43000. 38000. 33000. 28000. 23000. 18000. 13000.  8000.]
cumalative sales : 
 [[ 50000 102000 156000 212000]
 [ 45000  92000 141000 192000]
 [ 40000  82000 126000 172000]
 [ 35000  72000 111000 152000]
 [ 30000  62000  96000 132000]
 [ 25000  52000  81000 112000]
 [ 20000  42000  66000  92000]
 [ 15000  32000  51000  72000]
 [ 10000  22000  36000  52000]
 [  5000  12000  21000  32000]]


---