---
# Phase II : Numpy array operation
---
This notebook provides a comprehensive guide to various operations on NumPy arrays. It covers the following topics:

1. **Numpy array slicing**:
    - 1D array slicing: Demonstrates basic slicing, slicing with steps, and negative slicing.
    - 2D array slicing: Shows how to access specific elements, entire rows, and entire columns.

2. **Sorting the arrays**:
    - Sorting a 1D array.
    - Sorting a 2D array by rows and columns.

3. **Filtering the arrays**:
    - Normal filtering: Extracting even numbers from an array.
    - Filtering with mask: Using a mask to filter elements less than 6.

4. **Fancy indexing vs numpy.where()**:
    - Fancy indexing: Accessing elements using a list of indices.
    - `numpy.where()`: Using conditions to filter and modify array elements.

5. **Adding and removing data**:
    - Adding arrays: Demonstrates element-wise addition and concatenation.
    - Adding rows and columns: Shows how to add new rows and columns to an array.
    - Deleting rows and columns: Demonstrates how to delete specific rows and columns from an array.

6. **Array compatibility**:
    - Checking the compatibility of array shapes for operations.

In [1]:
import numpy as np

---
## Numpy array slicing :-
---
##### 1D array(vector) slicing :

In [2]:
arr = np.array([1,2,3,4,5,6,7,8])

print("Basic slicing", arr[1:5])         

print("Slicing with steps", arr[0:6:3])

print("Negative slicing", arr[-5])

Basic slicing [2 3 4 5]
Slicing with steps [1 4]
Negative slicing 4


##### 2D array(matrix) slicing :

In [3]:
arr_2d = np.array([[1,2,3,4],
                   [5,6,7,8]])

print("Specific element : ", arr_2d[1,3])  

print("Entire row : ", arr_2d[0])

print("Entire column : ", arr_2d[:,3])     # : column represents all rows in that column,here its done to get only 3rd column

Specific element :  8
Entire row :  [1 2 3 4]
Entire column :  [4 8]


---
## Sorting the arrays :-
---

In [4]:
unsorted = np.array([6,4,5,3,7,5,2,5,8,8,4,2,1])

print("Sorted array : ", np.sort(unsorted))                      # Sorts the array in ascending order

arr_2d = np.array([[2,3],
                   [4,1],
                   [4,1]])

print("Sorted 2D array by row :", np.sort(arr_2d, axis=0))       # axis=0 represents row wise sorting
print("Sorted 2D array by column :", np.sort(arr_2d, axis=1))    # axis=1 represents column wise sorting

Sorted array :  [1 2 2 3 4 4 5 5 5 6 7 8 8]
Sorted 2D array by row : [[2 1]
 [4 1]
 [4 3]]
Sorted 2D array by column : [[2 3]
 [1 4]
 [1 4]]


---
## Filtering the arrays :-
---
##### Normal filtering :

In [5]:
num = np.array([1,2,3,4,5,6,7,8,9,10])

even_num = num[num % 2 == 0]             # here we are giving condition instead of index as it is valid in numpy

print("Even number : ", even_num)

Even number :  [ 2  4  6  8 10]


##### Filtering with mask :

In [6]:
mask = num < 6                           # mask is a boolean array which is used to filter the elements based on the condition

print("number smaller than 6 are ", num[mask])

number smaller than 6 are  [1 2 3 4 5]


---
## Fancy indexing vs numpy.where() :-
---

In [7]:
indices = [0,2,4]
print("Indices are ",num[indices])

where_result = np.where(num < 6)                # where function returns the indices of the elements which satisfies the condition
print("NP where ", num[where_result])

condition_array = np.where(num > 5,num*2, num)  # where function can also be used to replace the elements based on the condition
print(condition_array)


Indices are  [1 3 5]
NP where  [1 2 3 4 5]
[ 1  2  3  4  5 12 14 16 18 20]


### Difference between Normal Filtering, Filtering with Mask, and Using `numpy.where`

1. **Normal Filtering**:
    - Normal filtering involves directly applying a condition to the array to filter elements.

2. **Filtering with Mask**:
    - Filtering with a mask involves creating a boolean array (mask) that indicates which elements satisfy the condition.
    - The mask is then used to filter the elements.

3. **Using `numpy.where`**:
    - `numpy.where` can be used to find the indices of elements that satisfy a condition or to replace elements based on a condition.


---
## Adding and removing data :-
---

In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

not_combined = arr1 + arr2             # in numpy + operator dont concatenate the arrays, it adds the elements of the arrays
print(not_combined)

combined = np.concatenate((arr1,arr2)) # to concatenate the arrays we use concatenate function
print(combined)             



[5 7 9]
[1 2 3 4 5 6]


---
## Array compatibilty :-
---
##### numpy.shape usecase :

In [9]:
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])
arr_3 = np.array([0,0,0,0])

print("Compatibity shape : ", arr_1.shape == arr_2.shape) # numpy.shape returns the shape of the array

Compatibity shape :  True



##### Adding row or column in array :


In [10]:
orginal = np.array([[1,2],
                    [3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((orginal,new_row))          # vstack is used to add new row to the array
print("Orginal Array : \n", orginal)
print("with new row : \n",with_new_row)

new_column = np.array([[5],[6]])
with_new_column = np.hstack((orginal,new_column))    # hstack is used to add new column to the array

print("Orginal Array : \n",orginal)
print("with new column : \n",with_new_column) 


Orginal Array : 
 [[1 2]
 [3 4]]
with new row : 
 [[1 2]
 [3 4]
 [5 6]]
Orginal Array : 
 [[1 2]
 [3 4]]
with new column : 
 [[1 2 5]
 [3 4 6]]



##### Deleting the row or column from Array :


In [11]:
deleted_row = np.delete(orginal, 1, axis=0)            
print("Array after deleting row 1:\n", deleted_row)

# Deleting a column
deleted_column = np.delete(orginal, 1, axis=1)
print("Array after deleting column 1:\n", deleted_column)

Array after deleting row 1:
 [[1 2]]
Array after deleting column 1:
 [[1]
 [3]]
